//! `refineable!` - declarative companion-struct generator.
//!
//! Expands one invocation into the partial-override twin of a base struct:
//! a `*Refinement` with every field wrapped in [`Option`], plus `refine()`,
//! `from_full()`, and `is_empty()` methods. The purpose mirrors zed's
//! `#[derive(Refineable)]` proc-macro - engram does it with a tiny
//! declarative macro so the theme crate stays dependency-light.
//!
//! Base structs stay hand-written so their doc comments and field grouping
//! survive. The macro only generates the refinement companion and its
//! glue - a single source of truth for field names is the caller's
//! responsibility (which is the same trade-off proc-macro Refineable pays
//! in zed).
//!
//! # Usage
//!
//! ```ignore
//! refineable! {
//!     /// A partial [`ThemeColors`]. All fields optional.
//!     pub struct ThemeColorsRefinement refines ThemeColors {
//!         colors { background, text, accent, /* ... */ }
//!         nested { status: StatusColorsRefinement }
//!     }
//! }
//! ```
//!
//! All `colors { ... }` fields become `Option<Hsla>` with the color-string
//! serde adapter wired up. Each `nested { name: Ref }` field expects the
//! referenced type to implement its own `refine`, `from_full`, and
//! `is_empty` - typically itself generated by `refineable!`.

#[macro_export]
macro_rules! refineable {
    (
        $(#[$sm:meta])*
        $svis:vis struct $rname:ident refines $base:ident {
            colors { $($field:ident),* $(,)? }
            $( nested { $($nfield:ident : $nref:ident),* $(,)? } )?
        }
    ) => {
        $(#[$sm])*
        #[derive(
            ::std::fmt::Debug,
            ::std::clone::Clone,
            ::std::marker::Copy,
            ::std::default::Default,
            ::std::cmp::PartialEq,
            ::serde::Deserialize,
            ::serde::Serialize,
        )]
        #[serde(default, deny_unknown_fields)]
        $svis struct $rname {
            $(
                #[serde(
                    default,
                    with = "crate::color_string::opt",
                    skip_serializing_if = "::std::option::Option::is_none",
                )]
                pub $field: ::std::option::Option<::gpui::Hsla>,
            )*
            $($(
                #[serde(default)]
                pub $nfield: $nref,
            )*)?
        }

        impl $rname {
            /// Copy every `Some(..)` field of `self` onto `base`, leaving
            /// the rest of `base` untouched. Nested refinements are
            /// recursed into the same way.
            pub fn refine(self, base: &mut $base) {
                $(
                    if let Some(v) = self.$field {
                        base.$field = v;
                    }
                )*
                $($(
                    self.$nfield.refine(&mut base.$nfield);
                )*)?
            }

            /// Wrap every field of `base` in `Some`. Used to dump a fully
            /// resolved theme to JSON - nothing is skipped on serialize.
            pub fn from_full(base: &$base) -> Self {
                Self {
                    $( $field: ::std::option::Option::Some(base.$field), )*
                    $($( $nfield: <$nref>::from_full(&base.$nfield), )*)?
                }
            }

            /// True when no field is overridden. Used so parent refinements
            /// can skip empty sub-objects on serialize.
            pub fn is_empty(&self) -> bool {
                *self == Self::default()
            }
        }
    };
}
